name: Keep Hugging Face Space Alive
on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Space
        run: curl -s https://afnansadiq-testgenrag.hf.space/ > /dev/null
